#!/usr/bin/env python3
"""Writes openMenu/src/openmenu/src/ui/backdrop_texture.h: the 64x64 cloud texture of the web page's Dreamcast background, as RGB565 in the
PVR's twiddled order, ready to be copied into video memory. The picture is the one inside modules/background/dc-background.js of
DreamPiAutoToggle (adapted from Robert Dale Smith's VMU Icon Maker, MIT licence): pass the path of that file or of the PNG.

  python3 make_backdrop_texture.py path/to/dc-background.js > backdrop_texture.h"""
import base64
import io
import re
import sys

import numpy as np
from PIL import Image

import pvr

src = sys.argv[1]
if src.endswith(".png"):
    img = Image.open(src)
else:
    m = re.search(r"data:image/png;base64,([A-Za-z0-9+/=]+)", open(src).read())
    img = Image.open(io.BytesIO(base64.b64decode(m.group(1))))
img = img.convert("RGB")
assert img.size == (64, 64), img.size
rgb = np.array(img)
blob = pvr.encode(rgb, 0, twiddled=True)
data = np.frombuffer(blob[32:], dtype="<u2")
out = ["/*",
       " * File: backdrop_texture.h",
       " * Project: openmenu",
       " * The 64x64 cloud texture of the Dreamcast-style animated background, RGB565 in the PVR's twiddled order (8 KB).",
       " * The picture comes from background.js of the VMU Icon Maker by Robert Dale Smith (https://github.com/RobertDaleSmith/vmu-icon-maker),",
       " * MIT License, as used in the DreamPi Netswitch add-on's background module. Generated by tools/folders-theme/make_backdrop_texture.py.",
       " */",
       "",
       "#pragma once",
       "",
       "#include <stdint.h>",
       "",
       "static const uint16_t backdrop_texture_data[64 * 64] __attribute__((aligned(32))) = {"]
for i in range(0, len(data), 12):
    out.append("    " + ", ".join("0x%04X" % v for v in data[i:i + 12]) + ",")
out.append("};")
print("\n".join(out))
